# Model Configuration
model:
    model_name: AS_AGFormer
    n_layers: 26
    dim_in: 3
    dim_feat: 128
    dim_rep: 512
    dim_out: 3
    mlp_ratio: 4
    act_layer: gelu
    attn_drop: 0.0
    drop: 0.0
    drop_path: 0.0
    use_layer_scale: True
    layer_scale_init_value: 0.00001
    use_adaptive_fusion: True
    num_heads: 8
    qkv_bias: False
    qkv_scale: null
    hierarchical: False
    use_temporal_similarity: True
    neighbour_num: 2
    temporal_connection_len: 1
    use_tcn: False
    graph_only: False
    filter_widths: [3, 3, 3, 3]
    channels: 256
    dropout: 0.3
    n_frames: 81
  
# Data Configuration
data:
    data_root: data/motion3d/
    flip: True
    stride: 9
    num_joints: 17
    out_joints: 17
    test_augmentation: True
    data_augmentation: True
    reverse_augmentation: False
    out_all: True
    
# Training Configuration
training:
    learning_rate: 0.0005
    batch_size: 32
    test_batch_size: 16
    weight_decay: 0.01
    lr_decay: 0.99
    epochs: 90
    max_grad_norm: 1.0  

# Loss Weights
loss:
    lambda_3d_velocity: 20.0
    lambda_scale: 0.5
    lambda_remaining: 0.0
  
  